In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')

In [3]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(x)

[['Indonesia' 44.0 72000.0]
 ['Malaysia' 25.0 60000.0]
 ['Indonesia' 30.0 55000.0]
 ['Thailand' 38.0 61000.0]
 ['Thailand' 40.0 nan]
 ['Vietnam' 35.0 58000.0]
 ['Brunei' nan 52000.0]
 ['Vietnam' 48.0 79000.0]
 ['Laos' 50.0 83000.0]
 ['Singapura' 37.0 67000.0]]


In [5]:
print(y)

['No' 'Yes' 'yes' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [6]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [7]:
print(x)

[['Indonesia' 44.0 72000.0]
 ['Malaysia' 25.0 60000.0]
 ['Indonesia' 30.0 55000.0]
 ['Thailand' 38.0 61000.0]
 ['Thailand' 40.0 65222.22222222222]
 ['Vietnam' 35.0 58000.0]
 ['Brunei' 38.55555555555556 52000.0]
 ['Vietnam' 48.0 79000.0]
 ['Laos' 50.0 83000.0]
 ['Singapura' 37.0 67000.0]]


In [10]:
from sklearn.compose import  ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [11]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 25.0 60000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 30.0 55000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 65222.22222222222]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 35.0 58000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.55555555555556 52000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [12]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [13]:
print(y)

[0 1 2 0 1 1 0 1 0 1]


In [14]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state = 1)

In [15]:
print(x_train)

[[0.0 0.0 0.0 0.0 0.0 1.0 0.0 40.0 65222.22222222222]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 38.0 61000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 25.0 60000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 48.0 79000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 50.0 83000.0]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 35.0 58000.0]]


In [16]:
print(y_train)

[1 0 0 1 1 0 1]


In [17]:
print(y_test)

[2 1 0]


In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])

In [19]:
print(x_train)

[[0.0 0.0 0.0 -0.40824829046386296 0.0 1.5811388300841895
  -0.6324555320336758 0.0 -0.3394514291136119]
 [0.0 1.0 0.0 -0.40824829046386296 0.0 -0.6324555320336758
  -0.6324555320336758 0.508000508000762 0.40386016181721807]
 [0.0 0.0 0.0 -0.40824829046386296 0.0 1.5811388300841895
  -0.6324555320336758 -0.254000254000381 -0.8024979939557677]
 [0.0 0.0 0.0 2.4494897427831783 0.0 -0.6324555320336758
  -0.6324555320336758 -1.9050019050028575 -0.9121669172078574]
 [0.0 0.0 0.0 -0.40824829046386296 0.0 -0.6324555320336758
  1.5811388300841895 1.016001016001524 1.1715426245818454]
 [0.0 0.0 1.0 -0.40824829046386296 0.0 -0.6324555320336758
  -0.6324555320336758 1.270001270001905 1.6102183175902038]
 [0.0 0.0 0.0 -0.40824829046386296 0.0 -0.6324555320336758
  1.5811388300841895 -0.6350006350009525 -1.1315047637120366]]


In [20]:
print(x_test)

[[0.0 1.0 0.0 0.0 0.0 0.0 0.0 30.0 55000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 38.55555555555556 52000.0]]
